### ISSUE TITLE
建议：加入博文（Blogs）侧边栏分类

### ISSUE THREAD

**Issue by biglizi123** [EveSunMaple/Frosti#10]
![7A31F4C6C92D0D2F54233A92CDAE172A](https://github.com/user-attachments/assets/063af38e-b88f-43b2-9dcb-9c42ceac0a65)
现在的博文全部都放到一个栏里，即使有搜索功能每个博文有tag，其实也不太方便其他人（游客）来查看内容，当然自己整理博文的时候也会不太方便，建议加入分类，可以把不同博文分类存放，同时左侧blogs可以有二级下拉栏，显示对应的分类，这样会好很多，设置不同分类来放置博文。

**Comment by EveSunMaple** [comment]
好的，将在下个版本添加😊（估计是2.5.0正式版了）

**Comment by EveSunMaple** [comment]
最新版已发布 https://github.com/EveSunMaple/Frosti/releases/tag/v2.5.0

**Comment by EveSunMaple** [comment]
还有问题请留言，若无，将在下个修订版本关闭此 issue

**Comment by EveSunMaple** [comment]
https://github.com/EveSunMaple/Frosti/compare/v2.5.1...v2.5.2
