### ISSUE TITLE
Invalid `tabindex` on non-interactive element ul elements should not have `tabindex` attribute

### ISSUE THREAD

**Issue by Bigwind110** [EveSunMaple/Frosti#11]
调试发现无效标签tabindex 
ts should not have `tabindex` attribute
位于/src/components/HeaderMenu.astro:8:2
可以删除吗？

**Comment by Bigwind110** [comment]
每次刷新页面的时候右上角会有个月亮乱飞，我不知道这个问题如何定位
![image](https://github.com/user-attachments/assets/c1a05e3a-547b-4cfb-8208-82c85d350ba0)

**Comment by EveSunMaple** [comment]
> 每次刷新页面的时候右上角会有个月亮乱飞，我不知道这个问题如何定位
> ![image](https://github.com/user-attachments/assets/c1a05e3a-547b-4cfb-8208-82c85d350ba0)
> 

这个是因为daisyui的样式还没有加载出来的时候两个 svg 竖直排列了，下个版本会修改，感谢反馈😉

**Comment by Bigwind110** [comment]
在src/components/Header.astro目录文件下29行引入多的<Menu />（import Menu from "../components/HeaderMenu.astro";的 ）,会导致生成透明的一个Memu
![image](https://github.com/user-attachments/assets/1de04de4-4071-4cda-ad0a-75d734cf2ad7)

**Comment by EveSunMaple** [comment]
> 在src/components/Header.astro目录文件下29行引入多的<Menu />（import Menu from "../components/HeaderMenu.astro";的 ）,会导致生成透明的一个Memu
> ![image](https://github.com/user-attachments/assets/1de04de4-4071-4cda-ad0a-75d734cf2ad7)
> 

好的，我大概了解了😉

只是现在我在外面只有手机不方便修改，等我回去后看一下具体问题再修改

再次感谢反馈！（真的很谢谢你们光我一个人很容易略过一些问题）

**Comment by Bigwind110** [comment]
你很厉害的,感谢你的回复，我的前端技术比较差，正在研究在你的框架下加入花里胡哨的功能😉

**Comment by EveSunMaple** [comment]
好的，我已经修复所有的问题，包括您没有提到的部分都修正好了

![QQ_1722513548417](https://github.com/user-attachments/assets/4493ec2e-4b05-494c-a601-a7df1282fa86)

**Comment by Bigwind110** [comment]
非常漂亮，希望你的框架能更受欢迎

**Comment by Bigwind110** [comment]
非常漂亮，希望你的框架能更受欢迎
