### ISSUE TITLE
一些样式的可改进点

### ISSUE THREAD

**Issue by nick-cjyx9** [EveSunMaple/Frosti#13]
1. 表格加入分割线
2. 减少卡片上卡片的阴影（二重阴影）
3. 这个页面的 css 有问题
![Screenshot_2024-08-01-23-20-27-379_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/916017e2-71c7-45ac-9a96-2d990eb68e47)

5. error card 和 info card 的图标没 align 齐
![Screenshot_2024-08-01-23-22-24-202_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/ffda300d-58f2-47d5-930d-e312501719b3)

6. 主流的设计弱化了字体大小的对比，以灰度和粗细来突出主次关系。可以参考

7. 各级标题的字号可以参考 github-markdown-css，符合读者阅读习惯，看着更顺眼。除了文章，还有大多数页面字号也需要调整，举例：搜索结果和文章卡片的字号不齐

8. 引入 rss feed，或是提供选项

9. 这个 card 的颜色很亮
![Screenshot_2024-08-01-23-28-57-070_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/d9e33660-01ca-493c-9f3a-dc5259a2c55a)

10. footer 和卡片没分开
![Screenshot_2024-08-01-23-39-23-174_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/bdb3a611-be51-4582-9920-44233d41a125)

11. 越界的 latex 公式
![Screenshot_2024-08-01-23-40-37-437_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/0d55c8ba-2398-4d08-b0e4-1ec604c81310)

12. 不使用中文斜体并提供替代，关于这点你可以查阅w3c的中文排版标准和知乎

13. 提供 robots.txt 模板供用户配置

14. 关于 mdx component:

- collapse 行为异常，展开后无法点击 arrow 收回，手机端误触控件外却会收回（不应该用 daisy 内建的逻辑）
- link card 作为一个 card 不够紧凑（手机端）导致看起来像图片加描述

希望 frosi 和 astro 越来越好（！）

**Comment by EveSunMaple** [comment]
汇报：
1. 已添加
2. 已修改，标题阴影也删了
3. 这个badge过长一定会出现此问题，想想Link其实不重要就移除了这个badge
4. 一致
5. 在@Tikas 的帮助下整个主题排版已经改过了
6. 同上
7. 这个早就有了
8. 已修改
9. 这是我自己站点的问题，已修改
10.  - 13. 暂未修改

**Comment by EveSunMaple** [comment]
除了 问题11 其他皆以修改，请自行检查

> 问题11 到现在并没有一个公认的代替方法（至少我没看到），现在几乎所有（我这样说是可能有我没有看到的）的 markdown 渲染都是渲染中文斜体的，这里就不做修改了

**Comment by nick-cjyx9** [comment]
Good job!
