### ISSUE TITLE
无法使用Vercel  Web Analytics

### ISSUE THREAD

**Issue by ClearH-Git** [EveSunMaple/Frosti#14]
在astro.config.mjs文件夹中添加
  output: 'server',
  adapter: vercel({
    webAnalytics: {
      enabled: true,
    },
  }),
后无法进入/blog页面 

![image](https://github.com/user-attachments/assets/8076e002-bdd3-49be-9d55-ea3e070c2860)

**Comment by EveSunMaple** [comment]
你这里使用`output: 'server'`服务器端渲染输出，而不是一般生成静态文件。

原项目是为静态站点设计的，对于这部分我没有涉猎，可能存在如你所说的问题。这里有一个数据没有成功获取，我不知道具体原因，也无法直接给出解决方案。

建议使用原输出模式，Vercel Web Analytics应该也支持静态网站。不过上述两个内容我都没有尝试过，对于此 issue 我更倾向于第二个解决方案，这里我自己也会进行尝试，如果成功会及时回复。

**Comment by EveSunMaple** [comment]
我发现一个插件https://www.npmjs.com/package/@vercel/analytics，这也许有用

**Comment by EveSunMaple** [comment]
![vercel com_evesunmaples-projects_astro-web_speed-insights](https://github.com/user-attachments/assets/519ea014-942f-4071-9b08-ca803a06dc80)
这是我在vercel上面看到的

**Comment by EveSunMaple** [comment]
好的，我本地测试过了，不知道你那里是为什么

**Comment by EveSunMaple** [comment]
![image](https://github.com/user-attachments/assets/b1b15745-6a66-47e4-894a-772f68e8ba7c)

可以正常使用，下面的是我的配置：

![image](https://github.com/user-attachments/assets/f302a489-d30d-49ab-b071-8b3531cf060e)

**Comment by EveSunMaple** [comment]
噢确实，我尝试过了，blog页面会出问题，等我看一下

**Comment by EveSunMaple** [comment]
查阅了一些资料，server和static获取数据的方式不一样，这可能需要重写那一部分的逻辑

**Comment by EveSunMaple** [comment]
好的，我知道怎么办了

![image](https://github.com/user-attachments/assets/147ba695-5782-4c30-8698-93e53b8e5c65)

这个其实是支持静态网站的

![image](https://github.com/user-attachments/assets/0831512c-9bed-494f-b5c5-1dc62ef0c187)

配置改成这样即可

**Comment by EveSunMaple** [comment]
如果您明白了，请自己关闭此 Issue

**Comment by ClearH-Git** [comment]
谢谢 又嫖到了 开心的一天
