### ISSUE TITLE
Vercel部署出现的问题

### ISSUE THREAD

**Issue by lyx-JuneSnow** [EveSunMaple/Frosti#17]
<img width="1074" alt="Snipaste_2024-08-08_20-07-42" src="https://github.com/user-attachments/assets/948beb78-e198-4f99-8af3-24e0db8c0d9f">
你好，我遇到了这个问题，但不知道怎么解决，应该是pnpm-lock.yaml 文件中的依赖版本与 package.json 文件中的依赖版本不一致，但我不太会更改，可以麻烦指导一下吗，thx

**Comment by EveSunMaple** [comment]
运行命令：`pnpm update` 即可

**Comment by EveSunMaple** [comment]
相同问题已在 #8

**Comment by lyx-JuneSnow** [comment]
收到，感谢！另外我想问一个问题，就是如果这个主题后续你在Astro上更新一些优化的话，那我是不是需要重新再部署一次呀？

**Comment by EveSunMaple** [comment]
是的，您可以通过 github 自带的 compare 功能查找相邻版本号之间修改的内容。如果您不想这么麻烦，也可以把除了您博客文章、配置文件之外的内容全部覆盖一次。Frosti 目前主题与内容的分离做的还是可以的，基本不会有什么问题。

关于 Astro 的更新，我有计划打算写一个 CLI 程序帮助，可以关注一下。

**Comment by lyx-JuneSnow** [comment]
好的，感谢作者出彩的工作，祝好！
