### ISSUE TITLE
最新的2.5.2更新后访问本地页面MDX博客后会报错

### ISSUE THREAD

**Issue by Bigwind110** [EveSunMaple/Frosti#18]
![image](https://github.com/user-attachments/assets/4c9a939f-498b-4116-9ab3-5cd2a1aa09de)
![image](https://github.com/user-attachments/assets/f77a7301-ba42-40d2-abff-98de735b5565)
问题可能是 items 没有正确传递或初始化，导致在调用 map 函数时出现 undefined 错误，我的解决方法是在TimeLine.astro的111行加入const { items= [] } = Astro.props;修复

**Comment by EveSunMaple** [comment]
这是因为发布的 2.5.2 release 并没有更新 Timeline 的结构，所以用新格式会报错。

建议通过 Astro 的 CLI 向导安装本主题，发布 release 只是为了方便几个版本号之间通过 compare 更新。不建议直接下载 release ，因为它们可能不是最新的。

**Comment by Bigwind110** [comment]
我是用远程镜像合并的代码，重新安装对我来说工作量有点大😂

**Comment by EveSunMaple** [comment]
Frosti 目前主题和博客内容分的还是比较清楚的，你可以直接把除了博文以及配置文件之外的所有内容覆盖一遍

**Comment by Bigwind110** [comment]
好的，谢谢你的解答😀
