### ISSUE TITLE
vercel deploy help

### ISSUE THREAD

**Issue by JIeJaitt** [EveSunMaple/Frosti#2]
<img width="1308" alt="image" src="https://github.com/EveSunMaple/Frosti/assets/77219045/ad996c98-b76e-4c54-9cae-dd1de6c77f1e">

**Comment by EveSunMaple** [comment]
抱歉，仅凭一张图我不明白是哪里出来问题。

请问这个问题还存在吗？我看您最新的仓库里已经解决了此问题。😊

> 如果可以，请注明此问题出现的原因，以帮助以后可能会出现的同类问题。

**Comment by JIeJaitt** [comment]
@EveSunMaple 谢谢我已经解决了这个问题，我觉得这个问题是我使用astro自带的构建工具构建的主题源码就出问题了，但是我从GitHub仓库直接下载的源码是可以正常使用和部署在 Vercel
