### ISSUE TITLE
2.5.3 文章里面 Code 的复制按钮丢失

### ISSUE THREAD

**Issue by Satxm** [EveSunMaple/Frosti#20]
2.5.3 文章里面 Code 的复制按钮丢失
截图链接 https://frosti.saroprock.com/blog/how-to-customize-code-box
![2024-08-12_170414](https://github.com/user-attachments/assets/dc35b9ce-1cb4-4673-af7d-c8915f136c9a)

**Comment by EveSunMaple** [comment]
已发布修订版本 ： https://github.com/EveSunMaple/Frosti/releases/tag/v2.5.4

有关于 `astro-pagefind` 的问题需要作者的更新，这里我已经提交了一个 PR：https://github.com/shishkin/astro-pagefind/pull/88

**Comment by EveSunMaple** [comment]
根据项目维护者的反馈，他们希望将 astro-pagefind 保持为与 Swup 无关的库。所以我只能监听 Swup 事件，然后手动触发 astro:page-load 事件，来实现与 astro-pagefind 的集成。

热修复已发布：https://github.com/EveSunMaple/Frosti/releases/tag/v2.5.4-hotfix.1

若还有问题，请告诉我；若无其他问题，我会关闭此 Issue。
