### ISSUE TITLE
在手表上打开菜单时滑动界面，菜单会收回导致无法点击子菜单。

### ISSUE THREAD

**Issue by nuym** [EveSunMaple/Frosti#21]
Watch:Apple Watch Ultra 1
Bug:打开菜单时滑动界面，菜单会收回导致无法点击子菜单。
~~真的有人会在手表上看blog么？？？~~

https://github.com/user-attachments/assets/13ac3e1a-6698-4609-ae74-3410628556e9

**Comment by nuym** [comment]
似乎视频无法正常播放，补充链接:
https://drive.google.com/file/d/1xUQquXbG8YNOVY08PdBG4IQpMOikHTnI/view?usp=sharing

**Comment by EveSunMaple** [comment]
这个是 daisyUI 内建的逻辑，点击元素外面会收回。

刚好 #13 中也提到了关于此逻辑的问题，到时候一起解决。

**Comment by EveSunMaple** [comment]
此问题已修复 https://github.com/EveSunMaple/Frosti/releases/tag/v2.5.5

**Comment by EveSunMaple** [comment]
根据其他用户的反馈，我将把导航栏逻辑改为原逻辑（点击外部收回），如果您特别需要支持在页面滚动时的菜单常驻，可以自行选择不更新主题。
