### ISSUE TITLE
How to Update

### ISSUE THREAD

**Issue by yaotutu** [EveSunMaple/Frosti#22]
When I use `npm create astro@latest -- --template EveSunMaple/Frosti`  to create a project, and if the project gets updated, how can I update the theme?”

**Comment by EveSunMaple** [comment]
Yes, Astro Project updates are indeed a big problem, and I have made some efforts as follows:
 
1. Frosti itself has achieved the separation of theme and page content, so you can directly overwrite all content except for configuration files and blogs;
2. I am writing a program to help update topics, but it is still very incomplete. https://github.com/EveSunMaple/astro-update-theme
 
In general, if you need to update the theme, you can now keep the `astro.config.mjs`, `consts.ts`, and `/blog` files, and then overwrite all other files.Finally, the most important step is to compare the contents of `astro.config.mjs` and `consts.ts` on your own to ensure that the new configuration items have been configured.Then, you can continue using the Frosti theme!
