### ISSUE TITLE
建议做一个图片大图查看的功能

### ISSUE THREAD

**Issue by che11111** [EveSunMaple/Frosti#24]
没有大图查看、还是有点小难受、、

可以参考下面两个

[medium-zoom](https://github.com/francoischalifour/medium-zoom)
[fancybox](http://fancyapps.com/fancybox/3/)

(๑◔‿◔๑)

**Comment by EveSunMaple** [comment]
已经添加，详见：https://github.com/EveSunMaple/Frosti/commit/de3d07122d4fe945e93906d52083c6b55195ed01

**Comment by che11111** [comment]
辛苦！
