### ISSUE TITLE
博客文章的html标题问题

### ISSUE THREAD

**Issue by Bigwind110** [EveSunMaple/Frosti#25]
**Title:** 🚀 博客文章的html标题问题
**Date:** [2024/8/22]

**Description:**
当我使用搜索引擎如google，bing时，发现自己的文章网页标题如图
![搜索引擎显示](https://i.p-i.vip/37/20240822-66c69d71efd7f.png)
![html元素显示](https://i.p-i.vip/37/20240822-66c69dba4e411.png)
我想要这个title标签自动为我的具体某篇文章标题的title，这样有利于我的博客文章被搜索引擎精准收录和帮助其他博友找到，否则我的所有博客在搜索引擎面前似乎标题都是blog，但由于我的前端不是很会，无法实现，请问作者大大是否有意添加这个功能？

BigWind
- Name: [BigWind]
- Email: [bigwind@bingwind.cn]

**Comment by EveSunMaple** [comment]
已修改 https://github.com/EveSunMaple/Frosti/releases/tag/v2.5.6

**Comment by Bigwind110** [comment]
非常感谢你，正是你的无私开源，使得互联网越来越好，祝好❤❤❤

**Comment by Bigwind110** [comment]
欢迎你来访我的博客[Bigwind](https://bigwind.cn/)，我已把你添加到友链，再次感谢你的贡献。

**Comment by EveSunMaple** [comment]
(*/ω＼*)
