### ISSUE TITLE
waline评论系统点击表情已不可用

### ISSUE THREAD

**Issue by Bigwind110** [EveSunMaple/Frosti#28]
**Title:** 🛠️ Bug Report: [waline评论系统点击表情已不可用]

**Date:** [08/30/2024]

**博客原文:** [🛠️ Bug Report: [waline评论系统点击表情已不可用]](https://bigwind.cn/blog/waline%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E8%A1%A8%E6%83%85%E5%88%86%E4%BA%AB/)
**Description:**
waline评论系统点击表情已不可用，报错如图，原因应该是原来框架的图床的桶设为私有或删除。
![](https://i.p-i.vip/37/20240828-66cf18a8a4050.png)
![](https://i.p-i.vip/37/20240828-66cf19588c1a7.png)

**Proposed Fix or Solution:**
修复建议：我将其表情迁移到我的两个图床上(由于图床限制，第一个图床不能使用png动图)，很高兴能在你的框架中使用，他们都是支持全球CDN访问的
这是gif格式，这个图床的链接将是长久的
>这个链接顺序是正确的，请放心
```astro
      "https://i.p-i.vip/37/20240828-66cf168c67b90.gif",
      "https://i.p-i.vip/37/20240828-66cf11c98f75c.gif",
      "https://i.p-i.vip/37/20240828-66cf16919077c.gif",
      "https://i.p-i.vip/37/20240828-66cf167ed75d1.gif",
      "https://i.p-i.vip/37/20240828-66cf168176744.gif",
      "https://i.p-i.vip/37/20240828-66cf16978ff66.gif",
      "https://i.p-i.vip/37/20240828-66cf13460d38a.gif",
      "https://i.p-i.vip/37/20240828-66cf1687607bb.gif",
```
png格式图床，这个图床是我自建的，所以有可能会被限速，但表情的下载速度问题应该不大
```astro
      "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/good.png",
      "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/bad.png",
      "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/happy.png",
      "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/color.png",
      "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/confuse.png",
      "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/heart.png",
      "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/rocket.png",
      "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/eyes.png",
```

**Contact Information:**
- Name: [BigWind]
- Email: [bigwind@bigwind.cn]

**Comment by Bigwind110** [comment]
> **标题：** 🛠️ Bug Report： [waline评论系统点击表情已不可用]
> 
> **日期：** [2024/08/30]**日期：**[2024/08/30]
> 
> **博客原文：** [🛠️ Bug Report： [waline评论系统点击表情已不可用]](https://bigwind.cn/blog/waline%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E8%A1%A8%E6%83%85%E5%88%86%E4%BA%AB/) **Description：** waline评论系统点击表情已不可用，报错如图，原因应该是原来框架的图床的桶设为私有或删除。 ![](https://camo.githubusercontent.com/0122e3f9331a36c7efe1226d2fa0f3ae509dc93a7feee3f1e2510ba6031fad85/68747470733a2f2f692e702d692e7669702f33372f32303234303832382d363663663138613861343035302e706e67) ![](https://camo.githubusercontent.com/a4546c6efc06ea72b7dbafe147d3c7ea3d2f04fd92d541b468f18c0cff67b090/68747470733a2f2f692e702d692e7669702f33372f32303234303832382d363663663139353838633161372e706e67)
> 
> **建议的修复或解决方案：** 修复建议：我将其表情迁移到我的两个图床上（由于图床限制，第一个图床不能使用png动图），很高兴能在你的框架中使用，他们都是支持全球CDN访问的 这是gif格式，这个图床的链接将是长久的
> 
> > 这个链接顺序是正确的，请放心
> 
> ```astro
>       "https://i.p-i.vip/37/20240828-66cf168c67b90.gif",
>       "https://i.p-i.vip/37/20240828-66cf11c98f75c.gif",
>       "https://i.p-i.vip/37/20240828-66cf16919077c.gif",
>       "https://i.p-i.vip/37/20240828-66cf167ed75d1.gif",
>       "https://i.p-i.vip/37/20240828-66cf168176744.gif",
>       "https://i.p-i.vip/37/20240828-66cf16978ff66.gif",
>       "https://i.p-i.vip/37/20240828-66cf13460d38a.gif",
>       "https://i.p-i.vip/37/20240828-66cf1687607bb.gif",
> ```
> 
> png格式图床，这个图床是我自建的，所以有可能会被限速，但表情的下载速度问题应该不大
> 
> ```astro
>       "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/good.png",
>       "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/bad.png",
>       "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/happy.png",
>       "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/color.png",
>       "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/confuse.png",
>       "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/heart.png",
>       "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/rocket.png",
>       "https://pub-e9759568a2dc405c9565f765445e931e.r2.dev/eyes.png",
> ```
> 
> **联系信息：**
> 
> * 名称：[BigWind]
> * 电子邮件： [[bigwind@bigwind.cn](mailto:bigwind@bigwind.cn)]电子邮件：[[bigwind@bigwind.cn](mailto:bigwind@bigwind.cn)]

补充报错图片
![image](https://github.com/user-attachments/assets/2a7151c1-e5f1-4293-927a-9c2be3a90f27)
![image](https://github.com/user-attachments/assets/39a095e3-e9ec-4cf6-a4fb-c631933cae52)

**Comment by EveSunMaple** [comment]
我的问题，没想到缤纷云的免费浏览用完了。

![84b8084c09bcb39d3d5d1a9517b79398](https://github.com/user-attachments/assets/e5766e78-dde0-4ee0-aeaa-74b1e248369f)

这里我自己会将此资源本地化，避免后续图床再次出现此问题。

**Comment by EveSunMaple** [comment]
已修复 https://github.com/EveSunMaple/Frosti/commit/f28eea98ce263b0127b078f349726245bb5505f6

**Comment by Bigwind110** [comment]
### 感谢你的及时回复和修复，你也可以选择使用我的cdn图床，尤其是自建的图床2，他们不是按流量计费的，全球速度也很好，因此不用担心费用😂，我很高兴能为这个开源项目提供帮助
