### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by Amezora** [EveSunMaple/Frosti#29]
在src/styles/global.scss中有一个apply拼写成了applt

**Comment by EveSunMaple** [comment]
好的，下次提交修改

**Comment by EveSunMaple** [comment]
本来想添加新功能后再修改，但是苦于没有时间……

这里提交了一个 hotfix，然后我将关闭此 issue https://github.com/EveSunMaple/Frosti/commit/15ca262833777fde419056774e29f5b0fd5dd7dc
