### ISSUE TITLE
代码框展示优化建议

### ISSUE THREAD

**Issue by liangyoufeng** [EveSunMaple/Frosti#3]
你好，看了一下你的博客主题还不错，希望可以在代码展示宽里配置显示行号和不同颜色的代码主题，主要防止代码太长了，复制的时候是不是同一行区分用的。祝好！

**Comment by EveSunMaple** [comment]
已采纳，详见[v2.3.0](https://github.com/EveSunMaple/Frosti/releases/tag/v2.3.0)

**Comment by EveSunMaple** [comment]
确认无误后再关闭 issue

**Comment by liangyoufeng** [comment]
谢谢！已更新验证。
