### ISSUE TITLE
谷歌浏览器点击home奔溃

### ISSUE THREAD

**Issue by cuncun-edg** [EveSunMaple/Frosti#31]
**Title:** 🛠️ Bug Report: [Brief Description of the Issue]
![image](https://github.com/user-attachments/assets/529aa5ee-aa5e-47bb-b9bf-a48ce3185074)
![image](https://github.com/user-attachments/assets/d2b47234-d776-43f6-a2f8-2e011a05f925)
已清楚缓存重试，都是一样的结果。
版本：版本 121.0.6167.140（正式版本） （64 位）

**Comment by YaoqxCN** [comment]
不太清楚这是什么问题，因为我这里是没正常的：

https://github.com/user-attachments/assets/dec02d21-982c-4f2d-8930-5f924792720d

*Chrome 版本：128.0.6613.114*

可能是您的 Chrome 版本问题？

**Comment by EveSunMaple** [comment]
您好 @cuncun-edg， 感谢您反馈此问题！

我尝试复现此报错，但没有成功。此问题通常是由插件冲突导致的。我使用的的 Chrome 版本为 `Version 128.0.6613.114 (Official Build) (64-bit)` ，同时，我并没有在 Chrome 中添加任何插件，在正常浏览操作下，没有出现崩溃的问题。

![image](https://github.com/user-attachments/assets/9657ccab-f528-4962-8957-d2fc04866530)

我也在我的 Edge 上访问了 Frosti Demo 主页。我使用的 Edge 版本为 `版本 128.0.2739.54 (正式版本) (64 位)`，装有 13 个插件，在正在浏览操作下，没有出现崩溃的问题。

![QQ_1725459437928](https://github.com/user-attachments/assets/70c853f0-b036-4df7-b7a8-b0e611a7beec)

于是我打算查找两个页面中不同的部分。但是您也看得到，两个页面都是由 `.mdx` 渲染而来，除了中央 `main` 之外没有任何不同。而 `main` 里面只有由 Markdown 渲染而来的内容，也没有任何可能产生冲突的代码。所以，现在我既无法复现问题，也找不到实质性的、可能存在问题的代码。我将给这个 issue 添加 `invaild` 标签以标记描述的错误无法复现。

如果可以，请提供更为详细的信息，或者提供冲突的位置。我不会关闭这个 issue，除非您一直不回复。

#### 补充

在 Frosti 早期曾出现过博客页面崩溃的问题，但是它是在我没有提交更改的情况下莫名其妙出现的。同样的，没几天后，它又莫名其妙消失了。如果您访问其他页面没有问题而光 Frosti Demo 有问题的话，那确实是我的博客主题存在一些潜在的、没有及时解决的问题。希望您可以帮助我们定位此问题，也希望 Frosti 更好。

感谢您的 issue ❤️

**Comment by EveSunMaple** [comment]
您好 @cuncun-edg， 感谢您反馈此问题！

我尝试复现此报错，但没有成功。此问题通常是由插件冲突导致的。我使用的的 Chrome 版本为 `Version 128.0.6613.114 (Official Build) (64-bit)` ，同时，我并没有在 Chrome 中添加任何插件，在正常浏览操作下，没有出现崩溃的问题。

![image](https://github.com/user-attachments/assets/9657ccab-f528-4962-8957-d2fc04866530)

我也在我的 Edge 上访问了 Frosti Demo 主页。我使用的 Edge 版本为 `版本 128.0.2739.54 (正式版本) (64 位)`，装有 13 个插件，在正在浏览操作下，没有出现崩溃的问题。

![QQ_1725459437928](https://github.com/user-attachments/assets/70c853f0-b036-4df7-b7a8-b0e611a7beec)

于是我打算查找两个页面中不同的部分。但是您也看得到，两个页面都是由 `.mdx` 渲染而来，除了中央 `main` 之外没有任何不同。而 `main` 里面只有由 Markdown 渲染而来的内容，也没有任何可能产生冲突的代码。所以，现在我既无法复现问题，也找不到实质性的、可能存在问题的代码。我将给这个 issue 添加 `invaild` 标签以标记描述的错误无法复现。

如果可以，请提供更为详细的信息，或者提供冲突的位置。我不会关闭这个 issue，除非您一直不回复。

#### 补充

在 Frosti 早期曾出现过博客页面崩溃的问题，但是它是在我没有提交更改的情况下莫名其妙出现的。同样的，没几天后，它又莫名其妙消失了。如果您访问其他页面没有问题而光 Frosti Demo 有问题的话，那确实是我的博客主题存在一些潜在的、没有及时解决的问题。希望您可以帮助我们定位此问题，也希望 Frosti 更好。

感谢您的 issue ❤️

**Comment by cuncun-edg** [comment]
经测试是我自己使用的谷歌版本问题，我使用的是Chrome_121.0.6167.140_64bit_Portable，我用edge也是正常的，抱歉了。
