### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by Loping151** [EveSunMaple/Frosti#37]
`./src/pages/blog/tag/[tag]/[...page].astro` line 61,

`./src/pages/blog/categories/[category]/[...page].astro` line 61,

```astro
    <h1 id="h1">{`${t("label.tagPage")} + ${params.tag}`}</h1>
    <h1 id="h1">{`${t("label.categoryPage")} + ${params.category}`}</h1>
```

这个`+`建议去掉。否则显示的似乎会是如： “标签 - + 随笔” 这样？看着很奇怪。

**Comment by EveSunMaple** [comment]
啊，本来应该是 “-”，写的时候没带脑子想着连接就变成加号了，非常抱歉。可以的话，希望提一个 PR ，因为我现在无法修改🙏

**Comment by EveSunMaple** [comment]
已经修复，非常感谢您。是我太着急了，晚上我会再审查一遍 2.6.0 ，稍后发布 hotfix

**Comment by Loping151** [comment]
emm这样改的话注意顺便修改`public/locales/xx/translation.json`里的`categoryPage`，不然就有两个 -- 了😂

别处应该问题不大，我也基本看过了。非常感谢您的Project~

**Comment by EveSunMaple** [comment]
哦对，我又犯浑了，原来的加是链接字符串，这个加就是字符串……太蠢了😥
