### ISSUE TITLE
建议：项目结构优化

### ISSUE THREAD

**Issue by Tikas** [EveSunMaple/Frosti#4]
难得在 B 站看到有 Astro，深夜起来点星星，然而，看了一下项目代码，和我预期的非常远。

我是 [volantis-go](https://github.com/volantis-x/volantis-go) 的项目负责人，也是使用 Astro ，项目现处于施工状态，对整个项目有着非常严格的易上手要求。

易上手，不仅是对那些会 Astro 的人，同时也对那些完全不懂的人，这是一件值得挑战去完成的事。

以下是一个来自刚学 CSS，同时不懂 JS / TS 的开发者建议，对，你没看错，我刚学，这是真的：

1、配置尽可能在少量配置文件里
2、如果面向非 Astro 用户，或者非前端开发用户，建议增加配置注释
3、项目结构能更合理些，现阶段比较错乱，比如，footer 不应该在 main 里等

由于我刚学，对 tailwindcss 这些不会，加上现有的项目也是业余抽空去开发，无法参与进来，对此，非常抱歉。

同时，我也希望能有更多的国人使用 Astro 去替代 Hexo，Volantis-go 就是我的一小步，希望我这个项目能给你带来一些启发。

**Comment by EveSunMaple** [comment]
您说的很对。事实上不仅这个项目是从零到一搭建起来的，我自己也是从“啥也不会”慢慢自学起来的。不过这个不能成为我项目结构混乱的借口，确实，我既然已经把这个项目作为模板放出，就应该有合理的项目结构以及上手教程。

我觉得这个确实是比较要紧的工作，我打算在这两天内完成项目清理工作，因为两天后我要去外地培训没有足够的时间维护了（学生党落泪），届时我发布后烦请您在检查一次，这里更新一下 To Do List：

- 当前 Astro 自动添加 `npm run check` 之后我的项目无法通过，这是因为生成博客的部分存在报错。事实上 `npx astro build` 不会有什么问题，但是出于对这个项目负责任的态度，我必须解决这一点
- 当前 `global.sass` 中大量使用了 apply ，我不知道这个合不合理，考虑到便于修改而且可以引入 daisyui 的样式才考虑的。我也不是专业的开发者，这个是否要更改还有待商榷
- 项目结构确实有问题，这部分我会请教一下 @WRXinYue 
- 配置文件是我自己摆烂了，您应该还可以看见我刚开始做项目留下的玩意……这个我在这几天会完善的
- 18n 是我自己的计划，不过这个估计要放到以后了，暂时没有学过

最后感谢您的 issue ！对我而言最享受的就是大家一起建言献策的过程。当原作者疏忽或者偷懒时（比如我自己）、项目本身还有待改进时，任何合理的建议都可以使这个项目日趋完美，即使您无法直接参与进来，对我的影响也是巨大的。

我愿意对这个项目保持一个负责的态度。不仅希望 Frosti 越来越好，也希望这样的环境可以一直保持下去😊

**Comment by EveSunMaple** [comment]
对了，我发现 Astro 主题更新特别麻烦，它并不能像 Hexo 一样让主题与博客内容分离……这个也许可以作为**易上手**的方面来考虑

**Comment by Tikas** [comment]
刚到公司，为你的态度点赞，太强了！

是的，Astro 虽然有很多优势，如果想单独开发出主题让人便捷使用，这非常糟糕，我在项目开始前，也是思考了这个问题。

我的解决方案是分离内容。

这样用户完全可以自己创建一个 git 内容仓库，他只需要更新自己的内容即可。

平时更新主题，只需要 pull 主题仓库，如此能完美解决。

i18n 多语言，我也考虑过，如果使用多语言，整个内容结构会改变，我的解决方法是：为主题开发两个版本，一个单语言，一个多语言。

正是因为我在项目开始之前就思考了更长远的问题，所以，也决定把配置放进内容区，这能让用户更方便维护。

另外，我也是刚学 CSS，很多东西都是要查阅 MDN 等网站才能进一步知晓其作用，我们大可不必使用尊称，不然，我也得用上。

加油，感谢您的认真的态度！

**Comment by EveSunMaple** [comment]
OK，我做了一些工作，详见 [v2.4.0](https://github.com/EveSunMaple/Frosti/releases/tag/v2.4.0)。

我已经把主要内容都移动到了 consts.st，也解决了**所有**的 error。现在 Frosti 已经可以通过 `npx astro check`。

Frosti 的 2.4 版本就是来解决项目结构问题的，这算是取得了一个阶段性的成就。届时修订版本将发布在 2.4.x。

此回复仅为提醒，一次更新肯定解决不了所有问题，难免存在疏漏，还有问题与建议请留言 😊

**Comment by Tikas** [comment]
壮举！庆祝！

由于我对 tailwindcss 以及 js / ts 不懂，很多修改跳过，同时，我并没有本地运行，是否能通过检测之类的判断。

以上的行为，主要也是自己真的不懂这些，无法参与进来优化。

以下就对现阶段我所掌握的知识，进行一些细微的分析：

1、分离图标是个不错的主意，这也在我的思考范围，我也在想着后续怎么处理图标。
2、html 的结构更具有语义化，这是良好的发展，后续的功能增减，可以建立在这基础上。
3、ts 的不知道叫什么的声明，可以写在前面珊格块里（不知道是不是这样描述）。

这里就第三点进行详细说一下，我有注意到两个非常有意思的修改：

A：`src/pages/blog/[...page].astro`
B：`src/pages/blog/tag/[tag]/[...page].astro`
 
A 文件在 --- 的珊格栏里有声明一个 Post 的不知道叫什么的声明，很抱歉，我真的对这些不懂，只有以这方式去描述。
他在 html 代码里引入时，被 (post: Post) 使用，这方式是对的，但是，好像可以在珊格栏里进一步声明，这样，html 代码里直接不用引入这个声明，这可以后续来优化。

有意思的地方来了：

B 文件里由于没在 --- 珊格栏里进行声明，我注意到这些全部声明为 any，这好像是为了过检测而设置。其实完全可以使用 A 文件的方式，进行声明并使用。

你的一小步改进，我只能看懂部分，当你的一大步改进，我只能向你提问学习了。

加油！

**Comment by EveSunMaple** [comment]
噢对，这个是我疏忽了 😥

原本两个方式都是一样的，都是 `const { page } = Astro.props;` ，但是 A 文件会报 never 错误， B 文件不会（因为它们的 Astro.props 略有不同）。所以改的时候我只在 A 中添加了结构声明而没有在 B 中添加（B 能跑就没动 🥺）。现在我新建了一个 `types.ts` 添加了 Post 和 Page 类型声明，import 取代了 B 文件中原本的 any 类型，两者统一了。

不过并不能直接使用 A 文件的方式，在 B 文件中使用类型注释是过不去的，会与 Astro.props 冲突。于是我使用了断言强制界定了 Astro.props 的类型。虽然 check 没有问题起来也更统一了，但总感觉哪里不太好 🤔。

---

上面是昨天晚上看到写的

---

我重写了页面，因为添加了很多内容但是又没有改好，这里发行为内部版本，详见[v2.5.0-alpha](https://github.com/EveSunMaple/Frosti/releases/tag/v2.5.0-alpha)

改的很多，可惜没有清理完 `global.scss`。我从今天开始要去外边上课，接下来十天做不到这么勤快了（不知道有没有机会）。还有建议请留言，小问题我会趁手改掉，大的修改比如 `global.scss` 可能要拖到十天后了。

**Comment by EveSunMaple** [comment]
已发布 rc 版本，此 issue 已经进入了最后的审查工作，博客在近期也不会再添加新功能。如果没有问题，将在 2.5.0 稳定版发布时关闭此 issue。

**Comment by EveSunMaple** [comment]
在发布 2.5.0 与解决 #11 中提到的问题后，我认为此 issue 可以关闭了。若后续还有问题，可以再次打开此 issue。
