### ISSUE TITLE
图片放大功能 显示bug

### ISSUE THREAD

**Issue by Loping151** [EveSunMaple/Frosti#47]
当某页面是通过一个其他页面跳转至的时候，该页面上的图片放大功能是正常的。

而当直接访问某页面时，或者刷新一次页面也是等效的，图片放大时会出现一个暗层，点击后才是正常显示图片。看起来似乎像是有一个图片上方的遮罩被一起放大了，不清楚和之前的主题切换渐变是不是有关系。bug触发方式有些变态了。我暂时没什么头绪。

可以通过 https://frosti.saroprock.com/blog/using-mdx-copy 中的图片复现

**Comment by Loping151** [comment]
![image](https://github.com/user-attachments/assets/b037287b-f93c-4513-9704-849675ae1d9b)

的确，触发的时候多出了一层medium-zoom-overlay。。神奇

**Comment by EveSunMaple** [comment]
之前修改 事件监听 导致 `mediumZoom` 初始化了两次，现在已经修复了！感谢捉虫！
