### ISSUE TITLE
Bug：评论区表情点击后会放大图片

### ISSUE THREAD

**Issue by YaoqxCN** [EveSunMaple/Frosti#49]
**Title:** 🛠️ Bug Report: 评论区表情点击后会放大图片

**Date:** 2024.11.5

**Affected Version:** 2.7.1

**Description:**
如题

**Expected Result:**
作为一个互动按钮呆在那里

**Actual Result:**
表情图片放大，不合理

**Screenshots or Attachments:**

https://github.com/user-attachments/assets/cbf2d5ab-f2da-4881-adfa-cb43f4864316

**Contact Information:**

- Name: Yaoqx
- Email: 1064245198@qq.com

**Comment by Loping151** [comment]
鉴定了一下，触发方式和 https://github.com/EveSunMaple/Frosti/issues/47 中一样，需要进入后刷新才会出现。
疑似是和之前同样的问题。。监听事件什么我不了解，但我推测原先是先初始化了图片相关然后初始化交互覆盖了图片属性，刷新之后图片属性又回来了？

Quick fix：
src/layouts/BaseLayout.astro 141
`mediumZoom(".main-card img:not(.link-card img):not(.comment img)", {`
根源上避免评论部分图片放大。缺点是如果评论里回复了图片无法进行放大。但作为接入的东西不共享页面本身的属性应该还是比较合理的不然就容易有这种bug。。。

**Comment by EveSunMaple** [comment]
accept quick fix

**Comment by EveSunMaple** [comment]
在未来的某个版本，作为过渡的评论系统会被移除

**Comment by EveSunMaple** [comment]
下面这些问题都是 Waline 引起的……说实话这有些令人恼火
![QQ_1731203175578](https://github.com/user-attachments/assets/2634ba69-140a-4c70-a414-7564226ea2ee)
