### ISSUE TITLE
vercel 部署报错

### ISSUE THREAD

**Issue by ClearH-Git** [EveSunMaple/Frosti#8]
ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
![image](https://github.com/user-attachments/assets/6026934e-62f3-4759-8bed-dd475edc78c4)

这怎么解决

**Comment by EveSunMaple** [comment]
> pnpm-lock.yaml is not up to date with package.json

项目目录打开终端输入：`pnpm update`如果没有 pnpm 请自行安装。

完成后，请及时回复此条以便我检查问题是否解决。

感谢您使用 Frosti 主题 😊

**Comment by zigzagpig** [comment]
> > pnpm-lock.yaml is not up to date with package.json
> 
> 项目目录打开终端输入：`pnpm update`如果没有 pnpm 请自行安装。
> 
> 完成后，请及时回复此条以便我检查问题是否解决。
> 
> 感谢您使用 Frosti 主题 😊

我也遇到这个问题了,建议:
1.在usage后面加上pnpm的安装相关命令.
2.在readme最前面可以加上本仓库地址,不太好找.

**Comment by EveSunMaple** [comment]
好的，下个修订版本会改 README

若无其他问题，将在下个修订版本发布后关闭此 issue

**Comment by ClearH-Git** [comment]
我直接删除pnpm-lock.yaml文件解决了

**Comment by EveSunMaple** [comment]
> 我直接删除pnpm-lock.yaml文件解决了
> 

不使用pnpm build确实是可行的方法……

**Comment by EveSunMaple** [comment]
> 好的，下个修订版本会改 README
> 
> 若无其他问题，将在下个修订版本发布后关闭此 issue

已完成，仓库链接就在最上面的 Code 按钮里面
